### ISSUE TITLE
TypeError: undefined is not a function(near '...RNRegulaDocumentReader.prepareDatabase...')

### ISSUE THREAD

**Issue by poojadurge26** [regulaforensics/React-Native-DocumentReader#1]
TypeError: undefined is not a function(near '...RNRegulaDocumentReader.prepareDatabase...') I got this error while using react-native-document-reader-api  after running react-native run-android
and Java Model Exception: Java Model Status [src/main/java/com/regula/documentreader [in react-native-document-reader-api] is not on its project's build path] is displayed on vs code output.

 getData(){
    var licPath = Platform.OS === 'ios' ? (RNFS.MainBundlePath + "/regula.license") : "regula.license";
    console.log("console logs",licPath);
    var readFile = Platform.OS === 'ios' ? RNFS.readFile : RNFS.readFileAssets;
  
    RNRegulaDocumentReader.prepareDatabase("Full", (respond) => {
      console.log("console logs 2",respond);
      readFile(licPath, 'base64').then((res)=> {
        console.log("console logs 3",res);
    this.setState({fullName: "Initializing..."});

        RNRegulaDocumentReader.initializeReader({
          licenseKey: res
        }, (respond) => {
          console.log("console logs 2",respond);
          RNRegulaDocumentReader.getCanRFID((canRfid)=>{
            if(canRfid){
              this.setState({canRfid: true});
              this.setState({canRfidTitle: ''});
            }
          });
          RNRegulaDocumentReader.getAvailableScenarios((jstring) => {
            var scenariosTemp = JSON.parse(jstring);
            var scenarios = [];
            for (var i in scenariosTemp) {
              scenarios.push({
                label: Scenario.fromJson(typeof scenariosTemp[i] === "string" ? JSON.parse(scenariosTemp[i]) : scenariosTemp[i]).name,
                value: i
              });
            }
            for (var i in this.state.scenarios) {
              this.state.scenarios[i]["disabled"] = true;
            }
            for (var i in scenarios) {
              for (var j in this.state.scenarios) {
                if (scenarios[i]["label"] === this.state.scenarios[j]["label"]) {
                  this.state.scenarios[j]["disabled"] = false;
                }
              }
            }
            var todelete = [];
            for (var j in this.state.scenarios) {
              if (this.state.scenarios[j]["disabled"] === true) {
                todelete.push(j);
              }
            }
            for (i = todelete.length - 1; i >= 0; i--) {
              this.state.scenarios.splice(todelete[i], 1);
            }
            this.forceUpdate();
            RNRegulaDocumentReader.getDocumentReaderIsReady((isReady)=>{
              if(isReady === true || isReady === "YES"){
                this.setState({fullName: "Ready"});
            }else{
              this.setState({fullName: "Failed"});
            }
            });
          });
        })
      });
 });
}

**Comment by vyakimchik** [comment]
Hello. We've released the new SDK - 5.0.0 version. Please, try it out.
