### ISSUE TITLE
How to mount the regula.license

### ISSUE THREAD

**Issue by jctaveras** [regulaforensics/React-Native-DocumentReader#2]
I just created a testing React Native app with `npx react-native init testig` and I was wondering how did you mange to load the `regula.license` file into the device file system. I cloned this repo and checked the FS and saw that the file was there but when I tried to do the same in my testing app the file doesn't get mounted even if I put it in the `./ios/testing` folder. 

Can I get a hit on how did you mange to do this?

**Comment by vyakimchik** [comment]
Hello. You have to add the file to the Xcode project and add it to the needed target. This file was added to our demo project, therefore, it's enough for users to copy the file to the required directory to use it.
