### ISSUE TITLE
I cant get the app up and running in a device or emulator. 

### ISSUE THREAD

**Issue by mushtaque87** [regulaforensics/React-Native-DocumentReader#3]
I have followed all the process properly. The app also install successfully . But on app launch, It shows a below error. 

<img width="342" alt="Screen Shot 2020-07-08 at 7 27 19 PM" src="https://user-images.githubusercontent.com/1650870/86938068-0cd4b600-c151-11ea-9e55-365c1b2e2864.png">

**Comment by vyakimchik** [comment]
Hello. It seems that this is not an issue of our demo app. Does this issue reproduce with the current changes in the demo project where SDK 5.1 is used?

**Comment by mushtaque87** [comment]
No with updating to 5.1 This seems to be resolved.
